/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_kay_Main */

#ifndef _Included_io_kay_Main
#define _Included_io_kay_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_kay_Main
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_kay_Main_nativeMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
